version: '3'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - redis
      - mongo
    networks:
      - backend

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27021:27017"
    networks:
      - backend

  redis:
    image: redis:bullseye
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
        - backend

networks:
  backend: